"""Run after updating vendor/iro/iro.min.js to regenerate its firmware asset."""
from pathlib import Path
import gzip
root = Path(__file__).resolve().parents[1]
data = gzip.compress((root / 'vendor/iro/iro.min.js').read_bytes(), mtime=0)
rows = [', '.join(f'0x{b:02x}' for b in data[i:i+16]) for i in range(0, len(data), 16)]
(root / 'src/iro_asset.h').write_text('// Generated by scripts/embed_iro.py; iro.js 5.5.2, MPL-2.0.\n#pragma once\nconst uint8_t IRO_JS_GZ[] PROGMEM = {\n' + ',\n'.join(rows) + '\n};\n')
