[env:seeed_xiao_esp32c3]
platform = espressif32@7.1.3
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps =
    fastled/FastLED@3.10.3

platform_packages =
    platformio/tool-esptoolpy@~1.40501.0
